### ISSUE TITLE
On tick error. Possible conflict with autofill mod?

### ISSUE THREAD

**Issue by Glendening** [FKuerten/factorio-tree-growth-natural-expansion#1] opened 2017-05-06 04:01 UTC
Just loaded up my already running game with the Tree growth mods added.
Literally just standing there waiting to see what happens and after a minute or three boom, error and crash to main menu.

Error while running event tree-growth-natural-expansion::on_tick (ID 0)
Error while running event autofill::on_built_entity (ID 6)
__autofill__/control.lua:50: bad argument #2 to '__index' (string expected, got nil)
stack traceback:
	__tree-growth-natural-expansion__/control/expansion.lua:127: in function 'tryToSpawnTreeNearTree'
	__tree-growth-natural-expansion__/control/expansion.lua:135: in function 'spawnTreeNearTree'
	__tree-growth-natural-expansion__/control/expansion.lua:156: in function 'spawnTreesInChunk'
	__tree-growth-natural-expansion__/control/expansion.lua:167: in function '?'
	__tree-growth-natural-expansion__/control.lua:22: in function <__tree-growth-natural-expansion__/control.lua:19>

Need or want any more information?

**Comment by FKuerten** [comment] 2017-05-06 08:35
Thank you for the report.
Can reproduce with autofill.

It seems I am misusing the on_built_entity event (i.e, there is no player) which autofill did not expect.
Since this could happen with other mods than autofill I will look how to work around this.

**Comment by FKuerten** [comment] 2017-05-06 09:52
This should be resolved in 2.0.0. You will need to update all four mods as this is about the communication between them.

**Closed as completed by FKuerten** 2017-05-06 09:52 UTC

**Comment by Glendening** [comment] 2017-05-07 15:49
=D Thank you so much! Updating right now.
